In [1]:
import numpy as np
import pandas as pd
import os
import re

***IMPORTING CSV DATABASE***

In [17]:
pd.set_option('display.max_columns', None)

In [18]:
DATA_PTH  = "C:/PATRICIA/Ironhack/Projects/PROJECT-2/PROJECT-II/mining_projects.csv"

In [19]:
df_re = pd.read_csv(DATA_PTH, sep=';')
df_re.head()

,Project No.,Deposit No.,Company Name,Project Name,Location,Continent,"Status (2022), 1: Exploration/ Define resource; 2: Feasibility/ Pre-feasibility; 3: Construction; 4: Production; S: Suspending mining; T: Test of Metallurgical; D: Development licence; N: Not Use",Deposit type,"Resource (*10^4 t, REO, Total)",Grade (wt. %),La2O3,Ce2O3,Pr6O11,Nd2O3,Sm2O3,Eu2O3,Gd2O3,Tb4O7,Dy2O3,Ho2O3,Er2O3,Tm2O3,Yb2O3,Lu2O3,Y2O3,HREE percentage,REE pattern Ref.,Project and status Ref.,Deposit type Ref.,Resource and grade Ref.,Unnamed: 30
0,1,1.0,Lynas Rare Earths,Mount Weld,"Mount Weld, Australia",Australia,4,Carbonatite,300,"5,4","24,11212582","45,66210046","5,073566717","18,07458143","2,524099442","0,583460173","1,293759513","0,139523085","0,481988838","0,063419584","0,139523085","0,012683917","0,063419584",0,"1,775748351","3,970065956","Paulick and Machacek ,2017","Lynas, Annual Report 2021, https://lynasrareea...","Lynas, Lynas Rare Earths Limited CLSA Explorat...","Lynas, Lynas Rare Earths Limited CLSA Explorat...",NaN
1,2,2.0,MP Materials,Mountain Pass,"Central Mojave Desert, California, America",North America,4,Carbonatite,"418,3","8,9","33,20134024","49,10143162","4,294852269","12,0012184","0,807188547","0,106609808","0,197989644","0,06091989","0,045689918","0,015229973","0,015229973","0,015229973","0,015229973","0,015229973","0,106609808","0,487359123","Paulick and Machacek ,2017",https://mpmaterials.com/about/,"Long, K.R., Van Gosen, B.S., Foley, N.K., and ...","Long, K.R., Van Gosen, B.S., Foley, N.K., and ...",NaN
2,3,3.0,Iluka Resources Limited,Eneabba,"Eneabba, Western Australia, Australia",Australia,4,Placer,"7,29","0,09","23,3358923","45,80451814","4,063304028","14,21353385","2,502545588",0,"1,597376358",0,"0,909987376","0,112744641","0,478281399","0,067454059","0,439415013","0,052035988","6,422911253","10,08020609","Jaireth et al., 2014, OGR","ILUKA, ENEABBA MINERAL SANDS RECOVERY PROJECT ...","ILUKA, ENEABBA MINERAL SANDS RECOVERY PROJECT ...","ILUKA, ENEABBA MINERAL SANDS RECOVERY PROJECT ...",NaN
3,4,4.0,NaN,WIM100 (Wimmera„ÄÅMallee),"Wimmera & Mallee,Western Australia, Australia",Australia,2,Placer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://iluka.com/operations-resource-developm...,https://iluka.com/operations-resource-developm...,NaN,NaN
4,5,5.0,Australian Strategic Materials,Dubbo (Toongi),"Dubbo, New South Wales, Australia",Australia,4(2022),Alkaline rock,"55,63","0,74","19,57255343","36,89538808","4,049493813","14,17322835","2,137232846","0,112485939","2,137232846","0,337457818","2,024746907","0,337457818","1,124859393","0,112485939","1,012373453","0,112485939","15,86051744","23,05961755","Paulick, H., & Machacek, E. (2017). The global...",https://asm-au.com/dubbo-project-overview/reso...,"Spandler, C., & Morris, C. (2016). Geology and...","Australian Strategic Materials, Annual Report ...",NaN

***STANDARD CLEANING***

In [20]:
df_re.shape

(146, 31)

In [21]:
def cleaning(df):
    df=df.dropna(axis=0,how='all')
    df=df.dropna(axis=1,how='all')
    df = df.drop_duplicates()
    return df

In [22]:
cleaning(df_re).head(4)

,Project No.,Deposit No.,Company Name,Project Name,Location,Continent,"Status (2022), 1: Exploration/ Define resource; 2: Feasibility/ Pre-feasibility; 3: Construction; 4: Production; S: Suspending mining; T: Test of Metallurgical; D: Development licence; N: Not Use",Deposit type,"Resource (*10^4 t, REO, Total)",Grade (wt. %),La2O3,Ce2O3,Pr6O11,Nd2O3,Sm2O3,Eu2O3,Gd2O3,Tb4O7,Dy2O3,Ho2O3,Er2O3,Tm2O3,Yb2O3,Lu2O3,Y2O3,HREE percentage,REE pattern Ref.,Project and status Ref.,Deposit type Ref.,Resource and grade Ref.
0,1,1.0,Lynas Rare Earths,Mount Weld,"Mount Weld, Australia",Australia,4,Carbonatite,300,"5,4","24,11212582","45,66210046","5,073566717","18,07458143","2,524099442","0,583460173","1,293759513","0,139523085","0,481988838","0,063419584","0,139523085","0,012683917","0,063419584",0,"1,775748351","3,970065956","Paulick and Machacek ,2017","Lynas, Annual Report 2021, https://lynasrareea...","Lynas, Lynas Rare Earths Limited CLSA Explorat...","Lynas, Lynas Rare Earths Limited CLSA Explorat..."
1,2,2.0,MP Materials,Mountain Pass,"Central Mojave Desert, California, America",North America,4,Carbonatite,"418,3","8,9","33,20134024","49,10143162","4,294852269","12,0012184","0,807188547","0,106609808","0,197989644","0,06091989","0,045689918","0,015229973","0,015229973","0,015229973","0,015229973","0,015229973","0,106609808","0,487359123","Paulick and Machacek ,2017",https://mpmaterials.com/about/,"Long, K.R., Van Gosen, B.S., Foley, N.K., and ...","Long, K.R., Van Gosen, B.S., Foley, N.K., and ..."
2,3,3.0,Iluka Resources Limited,Eneabba,"Eneabba, Western Australia, Australia",Australia,4,Placer,"7,29","0,09","23,3358923","45,80451814","4,063304028","14,21353385","2,502545588",0,"1,597376358",0,"0,909987376","0,112744641","0,478281399","0,067454059","0,439415013","0,052035988","6,422911253","10,08020609","Jaireth et al., 2014, OGR","ILUKA, ENEABBA MINERAL SANDS RECOVERY PROJECT ...","ILUKA, ENEABBA MINERAL SANDS RECOVERY PROJECT ...","ILUKA, ENEABBA MINERAL SANDS RECOVERY PROJECT ..."
3,4,4.0,NaN,WIM100 (Wimmera„ÄÅMallee),"Wimmera & Mallee,Western Australia, Australia",Australia,2,Placer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://iluka.com/operations-resource-developm...,https://iluka.com/operations-resource-developm...,NaN

In [23]:
df_re.shape

(146, 31)

In [24]:
df_re.columns

Index(['Project No.', 'Deposit No.', 'Company Name', 'Project Name',
       'Location', 'Continent',
       ' Status (2022), 1: Exploration/ Define resource; 2: Feasibility/ Pre-feasibility; 3: Construction; 4: Production; S: Suspending mining; T: Test of Metallurgical; D: Development licence; N: Not Use',
       'Deposit type', 'Resource (*10^4 t, REO, Total)', 'Grade (wt. %)',
       'La2O3', 'Ce2O3', 'Pr6O11', 'Nd2O3', 'Sm2O3', 'Eu2O3', 'Gd2O3', 'Tb4O7',
       'Dy2O3', 'Ho2O3', 'Er2O3', 'Tm2O3', 'Yb2O3', 'Lu2O3', 'Y2O3',
       'HREE percentage', 'REE pattern Ref.', 'Project and status Ref.',
       'Deposit type Ref.', 'Resource and grade Ref.', 'Unnamed: 30'],
      dtype='object')



***CHECKING DATA TYPES***
As we want to make math operations all values of columns we want to use for those calculations must be numbers.
If they are not we must create a fucntion to cast them to floats

In [25]:
df_re.dtypes

Project No.                                                                                                                                                                                               int64
Deposit No.                                                                                                                                                                                             float64
Company Name                                                                                                                                                                                             object
Project Name                                                                                                                                                                                             object
Location                                                                                                                                                                                                 object
Continent                                                                                                                                                                                                object
 Status (2022), 1: Exploration/ Define resource; 2: Feasibility/ Pre-feasibility; 3: Construction; 4: Production; S: Suspending mining; T: Test of Metallurgical; D: Development licence; N: Not Use     object
Deposit type                                                                                                                                                                                             object
Resource (*10^4 t, REO, Total)                                                                                                                                                                           object
Grade (wt. %)                                                                                                                                                                                            object
La2O3                                                                                                                                                                                                    object
Ce2O3                                                                                                                                                                                                    object
Pr6O11                                                                                                                                                                                                   object
Nd2O3                                                                                                                                                                                                    object
Sm2O3                                                                                                                                                                                                    object
Eu2O3                                                                                                                                                                                                    object
Gd2O3                                                                                                                                                                                                    object
Tb4O7                                                                                                                                                                                                    object
Dy2O3                                                                                                                                                                                                    object
Ho2O3                                                                                                                                                                                                    object
Er2O3                                                                                                                                                                                                    object
Tm2O3                                                                                                                                                                                                    object
Yb2O3                                                                                                                                                                                                    object
Lu2O3                                                                                                                                                                                                    object
Y2O3                                                                                                                                                                                                     object
HREE percentage                                                                                                                                                                                          object
REE pattern Ref.                                                                                                                                                                                         object
Project and status Ref.                                                                                                                                                                                  object
Deposit type Ref.                                                                                                                                                                                        object
Resource and grade Ref.                                                                                                                                                                                  object
Unnamed: 30                                                                                                                                                                                             float64
dtype: object

In [26]:
#as many numerical values are object type we cannot make numerical calculations with them. 
#We define a fucntion to convert them into floats

def into_float (df,list_of_columns):
    for col in list_of_columns:
        if col != 'NaN':
            df[col].replace(to_replace=['-'],value='nan',inplace=True)
            df[col]= df[col].str.replace(',', '.').astype(float)
        else:
            col
    return df

In [27]:
list_of_columns= ['Resource (*10^4 t, REO, Total)', 'Grade (wt. %)',
       'La2O3', 'Ce2O3', 'Pr6O11', 'Nd2O3', 'Sm2O3', 'Eu2O3', 'Gd2O3', 'Tb4O7',
       'Dy2O3', 'Ho2O3', 'Er2O3', 'Tm2O3', 'Yb2O3', 'Lu2O3', 'Y2O3','HREE percentage']

In [29]:
into_float(df_re, list_of_columns)

,Project No.,Deposit No.,Company Name,Project Name,Location,Continent,"Status (2022), 1: Exploration/ Define resource; 2: Feasibility/ Pre-feasibility; 3: Construction; 4: Production; S: Suspending mining; T: Test of Metallurgical; D: Development licence; N: Not Use",Deposit type,"Resource (*10^4 t, REO, Total)",Grade (wt. %),La2O3,Ce2O3,Pr6O11,Nd2O3,Sm2O3,Eu2O3,Gd2O3,Tb4O7,Dy2O3,Ho2O3,Er2O3,Tm2O3,Yb2O3,Lu2O3,Y2O3,HREE percentage,REE pattern Ref.,Project and status Ref.,Deposit type Ref.,Resource and grade Ref.,Unnamed: 30
0,1,1.0,Lynas Rare Earths,Mount Weld,"Mount Weld, Australia",Australia,4,Carbonatite,300.00,5.40,24.112126,45.662100,5.073567,18.074581,2.524099,0.583460,1.293760,0.139523,0.481989,0.063420,0.139523,0.012684,0.063420,0.000000,1.775748,3.970066,"Paulick and Machacek ,2017","Lynas, Annual Report 2021, https://lynasrareea...","Lynas, Lynas Rare Earths Limited CLSA Explorat...","Lynas, Lynas Rare Earths Limited CLSA Explorat...",NaN
1,2,2.0,MP Materials,Mountain Pass,"Central Mojave Desert, California, America",North America,4,Carbonatite,418.30,8.90,33.201340,49.101432,4.294852,12.001218,0.807189,0.106610,0.197990,0.060920,0.045690,0.015230,0.015230,0.015230,0.015230,0.015230,0.106610,0.487359,"Paulick and Machacek ,2017",https://mpmaterials.com/about/,"Long, K.R., Van Gosen, B.S., Foley, N.K., and ...","Long, K.R., Van Gosen, B.S., Foley, N.K., and ...",NaN
2,3,3.0,Iluka Resources Limited,Eneabba,"Eneabba, Western Australia, Australia",Australia,4,Placer,7.29,0.09,23.335892,45.804518,4.063304,14.213534,2.502546,0.000000,1.597376,0.000000,0.909987,0.112745,0.478281,0.067454,0.439415,0.052036,6.422911,10.080206,"Jaireth et al., 2014, OGR","ILUKA, ENEABBA MINERAL SANDS RECOVERY PROJECT ...","ILUKA, ENEABBA MINERAL SANDS RECOVERY PROJECT ...","ILUKA, ENEABBA MINERAL SANDS RECOVERY PROJECT ...",NaN
3,4,4.0,NaN,WIM100 (Wimmera„ÄÅMallee),"Wimmera & Mallee,Western Australia, Australia",Australia,2,Placer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://iluka.com/operations-resource-developm...,https://iluka.com/operations-resource-developm...,NaN,NaN
4,5,5.0,Australian Strategic Materials,Dubbo (Toongi),"Dubbo, New South Wales, Australia",Australia,4(2022),Alkaline rock,55.63,0.74,19.572553,36.895388,4.049494,14.173228,2.137233,0.112486,2.137233,0.337458,2.024747,0.337458,1.124859,0.112486,1.012373,0.112486,15.860517,23.059618,"Paulick, H., & Machacek, E. (2017). The global...",https://asm-au.com/dubbo-project-overview/reso...,"Spandler, C., & Morris, C. (2016). Geology and...","Australian Strategic Materials, Annual Report ...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,142,120.0,NaN,Dalucao,China,Asia,4,Carbonatite,8.20,5.21,25.060692,41.819381,4.384719,14.333672,2.399292,0.715671,1.784797,0.240643,1.068981,0.185520,0.541605,0.068703,0.433573,0.062389,6.900362,11.286574,"Shu er al., 2019, Geochemical characteristics ...","Fan H R, Niu H C, Li X C, et al. The types, or...","Fan H R, Niu H C, Li X C, et al. The types, or...","Fan H R, Niu H C, Li X C, et al. The types, or...",NaN
142,143,121.0,NaN,Yangfang,China,Asia,4,Carbonatite,13.30,2.40,37.340000,46.880000,3.960000,10.240000,0.810000,0.100000,0.300000,0.040000,0.080000,0.020000,0.050000,0.010000,0.010000,0.000000,0.180000,0.690000,China Northern Rare Earth (Group)High-Tech Co....,https://pdf.dfcfw.com/pdf/H3_AP202105301494845...,https://pdf.dfcfw.com/pdf/H3_AP202105301494845...,https://pdf.dfcfw.com/pdf/H3_AP202105301494845...,NaN
143,144,122.0,NaN,Maoniuping,China,Asia,4,Carbonatite,317.00,2.95,20.639824,43.946931,4.384400,16.589278,2.657195,0.680333,2.094005,0.244293,1.090719,0.200312,0.601486,0.080313,0.437539,0.064478,6.288893,11.102037,China Northern Rare Earth (Group)High-Tech Co....,"Fan H R, Niu H C, Li X C, et al. The types, or...","Fan H R, Niu H C, Li X C, et al. The types, or...","Fan H R, Niu H C, Li X C, et al. The types, or...",NaN
144,145,123.0,NaN,Muluozhai,China,Asia,4,Carbonatite,10.00,3.97,26.264902,45.059291,4.689198,15.487427,2.223116,0.518131,1.309941,0.154004,0.641510,0.098580,0.238225,0.037304,0.228492,0.031004,3.018875,5.757934,"Ouyang and Liu, 2019, REE mineralization and c...","Fan H R, Niu H C, Li X C, et al. The types, or...","Fan H R, Niu H C, Li X C, et al. The types, or...","Fan H R, Niu H C, Li X C, et al. The types, or...",NaN
145,146,124.0,NaN,South China seven proveince,China,Asia,4,Clays,840.00,0.02,18.530000,3.610000,4.400000,17.640000,4.170000,0.560000,5.000000,0.830000,4.720000,0.830000,2.500000,0.420000,1.810000,0.140000,34.840000,51.090000,NaN,"Li, Y. H. M., Zhao, W. W. & Zhou, M.-F. Nature...","Li, Y. H. M., Zhao, W. W. & Zhou, M.-F. Nature...",Personal conmunacation with Prof. Hanjie Wen,NaN

In [30]:
#checking that the function has worked
df_re.dtypes

Project No.                                                                                                                                                                                               int64
Deposit No.                                                                                                                                                                                             float64
Company Name                                                                                                                                                                                             object
Project Name                                                                                                                                                                                             object
Location                                                                                                                                                                                                 object
Continent                                                                                                                                                                                                object
 Status (2022), 1: Exploration/ Define resource; 2: Feasibility/ Pre-feasibility; 3: Construction; 4: Production; S: Suspending mining; T: Test of Metallurgical; D: Development licence; N: Not Use     object
Deposit type                                                                                                                                                                                             object
Resource (*10^4 t, REO, Total)                                                                                                                                                                          float64
Grade (wt. %)                                                                                                                                                                                           float64
La2O3                                                                                                                                                                                                   float64
Ce2O3                                                                                                                                                                                                   float64
Pr6O11                                                                                                                                                                                                  float64
Nd2O3                                                                                                                                                                                                   float64
Sm2O3                                                                                                                                                                                                   float64
Eu2O3                                                                                                                                                                                                   float64
Gd2O3                                                                                                                                                                                                   float64
Tb4O7                                                                                                                                                                                                   float64
Dy2O3                                                                                                                                                                                                   float64
Ho2O3                                                                                                                                                                                                   float64
Er2O3                                                                                                                                                                                                   float64
Tm2O3                                                                                                                                                                                                   float64
Yb2O3                                                                                                                                                                                                   float64
Lu2O3                                                                                                                                                                                                   float64
Y2O3                                                                                                                                                                                                    float64
HREE percentage                                                                                                                                                                                         float64
REE pattern Ref.                                                                                                                                                                                         object
Project and status Ref.                                                                                                                                                                                  object
Deposit type Ref.                                                                                                                                                                                        object
Resource and grade Ref.                                                                                                                                                                                  object
Unnamed: 30                                                                                                                                                                                             float64
dtype: object

In [31]:
#last verification: if we sum the columns with all the % values of the different components the result must be 100
columns_to_sum = ['La2O3', 'Ce2O3', 'Pr6O11', 'Nd2O3', 'Sm2O3', 'Eu2O3', 'Gd2O3', 'Tb4O7',
       'Dy2O3', 'Ho2O3', 'Er2O3', 'Tm2O3', 'Yb2O3', 'Lu2O3', 'Y2O3']

# Calculate the sum of the specified columns in the first row
sum_result = df_re.loc[0, columns_to_sum].sum()
sum_result

99.999999999

***Exporting to the folder created for clean databases***

In [36]:
df_re.to_csv("C:/PATRICIA/Ironhack/Projects/PROJECT-2/PROJECT-II/Clean _databases/df_re.csv")

In [37]:
pwd

'C:\\PATRICIA\\Ironhack\\Projects\\PROJECT-2\\PROJECT-II'